
package org.coderic.ws.sunat.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "billService", targetNamespace = "http://service.sunat.gob.pe")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillService {


    /**
     * 
     * @param numeroComprobante
     * @param rucComprobante
     * @param serieComprobante
     * @param tipoComprobante
     * @return
     *     returns org.coderic.ws.sunat.wsdl.StatusResponse
     */
    @WebMethod(action = "urn:getStatusCdr")
    @WebResult(name = "statusCdr", targetNamespace = "")
    @RequestWrapper(localName = "getStatusCdr", targetNamespace = "http://service.sunat.gob.pe", className = "org.coderic.ws.sunat.wsdl.GetStatusCdr")
    @ResponseWrapper(localName = "getStatusCdrResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.coderic.ws.sunat.wsdl.GetStatusCdrResponse")
    @Action(input = "urn:getStatusCdr", output = "http://service.sunat.gob.pe/billService/getStatusCdrResponse")
    public StatusResponse getStatusCdr(
        @WebParam(name = "rucComprobante", targetNamespace = "")
        String rucComprobante,
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        String tipoComprobante,
        @WebParam(name = "serieComprobante", targetNamespace = "")
        String serieComprobante,
        @WebParam(name = "numeroComprobante", targetNamespace = "")
        Integer numeroComprobante);

    /**
     * 
     * @param numeroComprobante
     * @param rucComprobante
     * @param serieComprobante
     * @param tipoComprobante
     * @return
     *     returns org.coderic.ws.sunat.wsdl.StatusResponse
     */
    @WebMethod(action = "urn:getStatus")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "org.coderic.ws.sunat.wsdl.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.coderic.ws.sunat.wsdl.GetStatusResponse")
    @Action(input = "urn:getStatus", output = "http://service.sunat.gob.pe/billService/getStatusResponse")
    public StatusResponse getStatus(
        @WebParam(name = "rucComprobante", targetNamespace = "")
        String rucComprobante,
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        String tipoComprobante,
        @WebParam(name = "serieComprobante", targetNamespace = "")
        String serieComprobante,
        @WebParam(name = "numeroComprobante", targetNamespace = "")
        Integer numeroComprobante);

}
